apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpv
  labels:
    type: local
spec:
  storageClassName: hritvik
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"